# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: ignite3

x-ignite-def:
  &ignite-def
  image: apacheignite/ignite:3.0.0
  configs:
    - source: node_config
      target: /opt/ignite/etc/ignite-config.conf

services:
  node1:
    << : *ignite-def
    command: --node-name node1
    ports:
      - 10300:10300
      - 10800:10800
  node2:
    << : *ignite-def
    command: --node-name node2
    ports:
      - 10301:10300
      - 10801:10800
#  node3:
#    << : *ignite-def
#    command: --node-name node3
#    ports:
#      - 10302:10300
#      - 10802:10800
#  connector:
#    image: gridgain/cloud-connector:latest
#    networks:
#      - default
#    ports:
#      - 3200:3200
#    environment:
#      CONNECTOR_BASE_URL: http://connector:3200
#      CONNECTOR_NAME: IgniteSummit2025
#      CONNECTOR_USERNAME: "YOUR_EMAIL@YOUR.DOM"
#      CONNECTOR_PASSWORD: "YOUR_NEBULA_PASSWORD"
#      CONNECTOR_CC_URL: https://portal.gridgain.com
#    command: 
#      - "/bin/sh"
#      - "-c"
#      - "export LOGGING_LEVEL_ROOT=DEBUG; env|grep LOG;./connector.sh"
