# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "ignite2" ]
  pull_request:
    branches: [ "ignite2" ]

jobs:
  build-java8:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
        architecture: x64
    - name: Build with Maven (Linux Java 8)
      run: mvn clean package -P core
      
  build-java11:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        architecture: x64
    - name: Build with Maven (Linux Java 11)
      run: mvn clean package -P core

  build-java17:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        architecture: x64
    - name: Build with Maven (Linux Java 17)
      run: mvn clean package -P core

  build-java11-win:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11 Windows
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        architecture: x64
    - name: Build with Maven (Windows Java 11)
      run: mvn clean package -P core

  build-java11-mac:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11 Mac
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        architecture: arm64
    - name: Build with Maven (Mac Java 11)
      run: mvn clean package -P core
